services:
  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=anthropos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - wandering-digital-db:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  consul:
    image: hashicorp/consul
    ports:
      - 8500:8500

volumes:
  wandering-digital-db: